'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class loginGlobals
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.loginGlobals", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property lg_login_button_text() As String
            Get
                Return ResourceManager.GetString("lg_login_button_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attention Webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_attention_webmaster() As String
            Get
                Return ResourceManager.GetString("lg_phrase_attention_webmaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The account has been canceled..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_cancel_account_canceled() As String
            Get
                Return ResourceManager.GetString("lg_phrase_cancel_account_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error canceling your account. Please contact the webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_cancel_account_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_cancel_account_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your User ID and Password to cancel your account.&lt;p&gt;WARNING: THIS ACTION CAN NOT BE UNDONE.&lt;/p&gt;If you have forgotten your password use the recover password link below..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_cancel_account_warning() As String
            Get
                Return ResourceManager.GetString("lg_phrase_cancel_account_warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your current password, then your desired new password.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_change_password() As String
            Get
                Return ResourceManager.GetString("lg_phrase_change_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Confirm Password field is empty but is required. Please confirm your password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_confirm_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_confirm_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please confirm your desired password. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_confirm_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_confirm_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to contact the webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_contact_webmaster() As String
            Get
                Return ResourceManager.GetString("lg_phrase_contact_webmaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please contact the webmaster for assistance..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_contact_webmaster1() As String
            Get
                Return ResourceManager.GetString("lg_phrase_contact_webmaster1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Account.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_delete_account() As String
            Get
                Return ResourceManager.GetString("lg_phrase_delete_account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The account has already been verified and could not be deleted.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_delete_already_verified() As String
            Get
                Return ResourceManager.GetString("lg_phrase_delete_already_verified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The account has been deleted.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_delete_deleted() As String
            Get
                Return ResourceManager.GetString("lg_phrase_delete_deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Email field is empty but is required. Please enter your Email address..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_email_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_email_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your Email address. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_email_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_email_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter set new password token.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_enter_set_new_password_token() As String
            Get
                Return ResourceManager.GetString("lg_phrase_enter_set_new_password_token", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Unlock Code.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_enter_unlock_code() As String
            Get
                Return ResourceManager.GetString("lg_phrase_enter_unlock_code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your userid and Email to receive a new verification token..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_issue_new_token() As String
            Get
                Return ResourceManager.GetString("lg_phrase_issue_new_token", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error generating your verification token. Please contact the webmaster..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_issue_new_token_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_issue_new_token_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your new verification token will be mailed to your Email address..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_issue_new_token_success() As String
            Get
                Return ResourceManager.GetString("lg_phrase_issue_new_token_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is logged in..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_is_logged_in() As String
            Get
                Return ResourceManager.GetString("lg_phrase_is_logged_in", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are logged out..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_logged_out() As String
            Get
                Return ResourceManager.GetString("lg_phrase_logged_out", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error. Please re-enter your User ID and Password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_login_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_login_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Either the verification token has been used, (and you are verified,) or the token is not valid..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_login_token_problem() As String
            Get
                Return ResourceManager.GetString("lg_phrase_login_token_problem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to continue..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_logout_continue() As String
            Get
                Return ResourceManager.GetString("lg_phrase_logout_continue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Name field is empty but is required. Please enter your name..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_name_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_name_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your full name. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_name_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_name_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The New Password field is empty but is required. Please enter your new password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_newpassword_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_newpassword_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to receive periodic Emails when the website changes or new articles are posted?.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_news() As String
            Get
                Return ResourceManager.GetString("lg_phrase_news", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was no registration matching the User ID and Email address you entered..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_no_matching_registration() As String
            Get
                Return ResourceManager.GetString("lg_phrase_no_matching_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current password does not match your stored password. Try again..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_oldpassword_does_not_match() As String
            Get
                Return ResourceManager.GetString("lg_phrase_oldpassword_does_not_match", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Current Password field is empty but is required. Please enter your current password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_oldpassword_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_oldpassword_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your current password. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_oldpassword_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_oldpassword_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your password was changed..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_changed() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_changed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error. The password was not changed. Please contact the webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_changed_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_changed_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password changed successfully..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_changed_okay() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_changed_okay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  was changed at .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_changed_post() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_changed_post", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your password at .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_changed_pre() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_changed_pre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you did not authorize this change, please contact the webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_change_authorized() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_change_authorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Password field is empty but is required. Please enter your password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your desired password. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_new_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_new_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Password does not match the Confirmation Password. Please re-enter..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_nomatch_confirm() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_nomatch_confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your password. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_password_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_password_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recover Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You may set a new password by clicking the link below..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password2() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set New Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password3() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you did not request to recover your password, contact the webmaster by .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password4() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email at the following Email link .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password5() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error processing your request. Please contact the webmaster..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The request to recover your password was processed successfully.&lt;p&gt;Please follow the instructions in the Email sent to you to set a new password.&lt;/p&gt;.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_recover_password_success() As String
            Get
                Return ResourceManager.GetString("lg_phrase_recover_password_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was no account matching the email address you entered..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_register_delete_noemail() As String
            Get
                Return ResourceManager.GetString("lg_phrase_register_delete_noemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verify Your Email Address.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_email_verify() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_email_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Email was sent to the Email address you provided during registration.&amp;nbsp; Click the link in that Email or copy and paste the unlock code in the form field below. Your account will not be available until it has been verified..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_email_verify_msg() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_email_verify_msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error completing your registration. Please contact the webmaster.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issued New Registration Verification Token.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail0() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for registering at.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail1() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before you can login you need.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail2() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to to verify your Email address..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail3() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click Here To Verify.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail4() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If the above link does not work, go to &lt;p&gt;http://.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail5() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to copy and paste the token below into the form and click &quot;&quot;Submit&quot;&quot;.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail6() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you did not register, click.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail7() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to this link: &lt;a href=&quot;&quot;http://.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail8() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to if you have any questions then &lt;a href=&quot;&quot;http://.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_mail9() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_mail9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration Successful.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_registration_success() As String
            Get
                Return ResourceManager.GetString("lg_phrase_registration_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not check remember me if this is a shared computer..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_remember_me_warning() As String
            Get
                Return ResourceManager.GetString("lg_phrase_remember_me_warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A request has been made to recover your password at .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_request_password1() As String
            Get
                Return ResourceManager.GetString("lg_phrase_request_password1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an unexpected error in completing your request. .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_set_new_password_error() As String
            Get
                Return ResourceManager.GetString("lg_phrase_set_new_password_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your token was valid. Enter a new password..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_set_new_password_good_token() As String
            Get
                Return ResourceManager.GetString("lg_phrase_set_new_password_good_token", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your password was successfully changed..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_set_new_password_success() As String
            Get
                Return ResourceManager.GetString("lg_phrase_set_new_password_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More than 24 hours have passed since you requested a password recovery token..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_set_new_password_token_expired() As String
            Get
                Return ResourceManager.GetString("lg_phrase_set_new_password_token_expired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The User ID field is required but is empty. Please enter your User ID..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_userid_empty() As String
            Get
                Return ResourceManager.GetString("lg_phrase_userid_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The User ID is in use or invalid..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_userid_inuse() As String
            Get
                Return ResourceManager.GetString("lg_phrase_userid_inuse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your desired User ID. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_userid_new_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_userid_new_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your userid. This field is required..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_userid_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_userid_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Registration.
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_user_registration() As String
            Get
                Return ResourceManager.GetString("lg_phrase_user_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More than 24 hours have passed since your registration..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_verify_expired() As String
            Get
                Return ResourceManager.GetString("lg_phrase_verify_expired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You may now login to your account..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_verify_login() As String
            Get
                Return ResourceManager.GetString("lg_phrase_verify_login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to generate a new unlock code..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_verify_newtoken() As String
            Get
                Return ResourceManager.GetString("lg_phrase_verify_newtoken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have verified your email address..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_verify_verified() As String
            Get
                Return ResourceManager.GetString("lg_phrase_verify_verified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The webmaster may be contacted by Email using this link: .
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_webmaster_may_be_contacted() As String
            Get
                Return ResourceManager.GetString("lg_phrase_webmaster_may_be_contacted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your website address..
        '''</summary>
        Friend Shared ReadOnly Property lg_phrase_website_title() As String
            Get
                Return ResourceManager.GetString("lg_phrase_website_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register.
        '''</summary>
        Friend Shared ReadOnly Property lg_register_button_text() As String
            Get
                Return ResourceManager.GetString("lg_register_button_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to at.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_at() As String
            Get
                Return ResourceManager.GetString("lg_term_at", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Account.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_cancel() As String
            Get
                Return ResourceManager.GetString("lg_term_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Account.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_cancel_account() As String
            Get
                Return ResourceManager.GetString("lg_term_cancel_account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_change_password() As String
            Get
                Return ResourceManager.GetString("lg_term_change_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_change_password_button_text() As String
            Get
                Return ResourceManager.GetString("lg_term_change_password_button_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to checkToken.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_checkToken() As String
            Get
                Return ResourceManager.GetString("lg_term_checkToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_city() As String
            Get
                Return ResourceManager.GetString("lg_term_city", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_confirm() As String
            Get
                Return ResourceManager.GetString("lg_term_confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Form.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_contact_form() As String
            Get
                Return ResourceManager.GetString("lg_term_contact_form", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_country() As String
            Get
                Return ResourceManager.GetString("lg_term_country", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_current_password() As String
            Get
                Return ResourceManager.GetString("lg_term_current_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Account.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_delete_account() As String
            Get
                Return ResourceManager.GetString("lg_term_delete_account", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to doRegistration.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_do_registration() As String
            Get
                Return ResourceManager.GetString("lg_term_do_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_email() As String
            Get
                Return ResourceManager.GetString("lg_term_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Information.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_enter_information() As String
            Get
                Return ResourceManager.GetString("lg_term_enter_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to getPasshash.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_error_string() As String
            Get
                Return ResourceManager.GetString("lg_term_error_string", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Example.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_example() As String
            Get
                Return ResourceManager.GetString("lg_term_example", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Form Error.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_from_error() As String
            Get
                Return ResourceManager.GetString("lg_term_from_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to getName.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_get_name() As String
            Get
                Return ResourceManager.GetString("lg_term_get_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to getOldPassword.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_get_oldpassword() As String
            Get
                Return ResourceManager.GetString("lg_term_get_oldpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guest.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_guest() As String
            Get
                Return ResourceManager.GetString("lg_term_guest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_home() As String
            Get
                Return ResourceManager.GetString("lg_term_home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to immediately.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_immediately() As String
            Get
                Return ResourceManager.GetString("lg_term_immediately", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IP.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_ip() As String
            Get
                Return ResourceManager.GetString("lg_term_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issue Verification Token.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_issue_verification_token() As String
            Get
                Return ResourceManager.GetString("lg_term_issue_verification_token", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logged Out.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_logged_out() As String
            Get
                Return ResourceManager.GetString("lg_term_logged_out", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_login() As String
            Get
                Return ResourceManager.GetString("lg_term_login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_login_success() As String
            Get
                Return ResourceManager.GetString("lg_term_login_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log out.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_log_out() As String
            Get
                Return ResourceManager.GetString("lg_term_log_out", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to logLogin.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_log_string() As String
            Get
                Return ResourceManager.GetString("lg_term_log_string", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_name() As String
            Get
                Return ResourceManager.GetString("lg_term_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_new_password() As String
            Get
                Return ResourceManager.GetString("lg_term_new_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Optional.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_optional() As String
            Get
                Return ResourceManager.GetString("lg_term_optional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to or.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_or() As String
            Get
                Return ResourceManager.GetString("lg_term_or", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_password() As String
            Get
                Return ResourceManager.GetString("lg_term_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Login.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_please_login() As String
            Get
                Return ResourceManager.GetString("lg_term_please_login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Register.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_please_register() As String
            Get
                Return ResourceManager.GetString("lg_term_please_register", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recover Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_recover_password() As String
            Get
                Return ResourceManager.GetString("lg_term_recover_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Region.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_region() As String
            Get
                Return ResourceManager.GetString("lg_term_region", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_register() As String
            Get
                Return ResourceManager.GetString("lg_term_register", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_register_confirmation() As String
            Get
                Return ResourceManager.GetString("lg_term_register_confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Email.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_register_delete_enter_email() As String
            Get
                Return ResourceManager.GetString("lg_term_register_delete_enter_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_registration() As String
            Get
                Return ResourceManager.GetString("lg_term_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for registering..
        '''</summary>
        Friend Shared ReadOnly Property lg_term_registration_thankyou() As String
            Get
                Return ResourceManager.GetString("lg_term_registration_thankyou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration Verification.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_registration_verification() As String
            Get
                Return ResourceManager.GetString("lg_term_registration_verification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember Me.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_rememberme() As String
            Get
                Return ResourceManager.GetString("lg_term_rememberme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Registration.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_remove_registration() As String
            Get
                Return ResourceManager.GetString("lg_term_remove_registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to required.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_required() As String
            Get
                Return ResourceManager.GetString("lg_term_required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password Reset.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_reset_password() As String
            Get
                Return ResourceManager.GetString("lg_term_reset_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to changePassword.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_set_newpassword() As String
            Get
                Return ResourceManager.GetString("lg_term_set_newpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set New Password.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_set_new_password() As String
            Get
                Return ResourceManager.GetString("lg_term_set_new_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_submit() As String
            Get
                Return ResourceManager.GetString("lg_term_submit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To .
        '''</summary>
        Friend Shared ReadOnly Property lg_term_to() As String
            Get
                Return ResourceManager.GetString("lg_term_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Useragent.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_useragent() As String
            Get
                Return ResourceManager.GetString("lg_term_useragent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserID.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_userid() As String
            Get
                Return ResourceManager.GetString("lg_term_userid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to by email at.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_via_email() As String
            Get
                Return ResourceManager.GetString("lg_term_via_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_website() As String
            Get
                Return ResourceManager.GetString("lg_term_website", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website Address.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_website_address() As String
            Get
                Return ResourceManager.GetString("lg_term_website_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome.
        '''</summary>
        Friend Shared ReadOnly Property lg_term_welcome() As String
            Get
                Return ResourceManager.GetString("lg_term_welcome", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
